version: "4.0"
services:
  postgres:
    image: postgres:latest
    container_name: db_prueba
    restart: no
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${NAMEUSER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
