name: Publish Docker image to GHCR

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Por ejemplo, v1.0.0
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Necesario para publicar en ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name (lowercase)
        run: |
          OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$OWNER_LOWERCASE/to-do-list"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
